Command = Cmd {Data}.
Cmd = "next" | "move" | "undo" | "save" | "restore" |
      "show" | "quit" | "exit" | "clear".

Data = label | int | position.

label = letter {letter}.
int = digit {digit}.
position = letter digit.

letter = "a"|"b"|"c"|"d"|"e"|"f"|"g"|"h"|"i"|
         "j"|"k"|"l"|"m"|"n"|"o"|"p"|"q"|"r"|
		 "s"|"t"|"u"|"v"|"w"|"x"|"y"|"z"|
         "A"|"B"|"C"|"D"|"E"|"F"|"G"|"H"|"I"|
         "J"|"K"|"L"|"M"|"N"|"O"|"P"|"Q"|"R"|
		 "S"|"T"|"U"|"V"|"W"|"X"|"Y"|"Z"|"_".

digit = "0"|"1"|"2"|"3"|"4"|"5"|"6"|"7"|"8"|"9".
